In [1]:
import pandas as pd
import numpy as np


In [2]:
li=[1,2,3,4]

In [3]:
type(li)

list

In [5]:
x=np.array(li)

In [6]:
x

array([1, 2, 3, 4])

In [7]:
type(x)

numpy.ndarray

In [8]:
data1=np.array([1,2,"data2",4,None])

In [9]:
data1

array([1, 2, 'data2', 4, None], dtype=object)

In [10]:
data1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [14]:
data3=np.array([1,2,3,4,6,5])

In [15]:
data3

array([1, 2, 3, 4, 6, 5])

In [16]:
data3.sum()

21

In [17]:
data4=np.array([1,2,np.nan,3,4])

In [18]:
data4

array([ 1.,  2., nan,  3.,  4.])

In [19]:
type(data4)

numpy.ndarray

In [20]:
1+None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [21]:
1+np.nan

nan

In [22]:
data4.sum()

nan

In [23]:
0*np.nan

nan

In [24]:
y=pd.Series([1,2,3,np.nan,4])

In [25]:
y

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
dtype: float64

In [26]:
z=pd.Series([1,2,3,None,5])

In [27]:
z

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64

In [29]:
p=pd.Series(range(2), dtype=int)

In [30]:
p

0    0
1    1
dtype: int32

In [31]:
p[0]


0

In [32]:
p[1]

1

In [34]:
p[0]=np.nan

In [35]:
p

0    NaN
1    1.0
dtype: float64

In [36]:
k=np.array([1,2,3,True,7,False,np.nan])

In [37]:
k

array([ 1.,  2.,  3.,  1.,  7.,  0., nan])

In [38]:
k1=pd.Series([1,2,3,True,7,False,np.nan])

In [39]:
k1

0        1
1        2
2        3
3     True
4        7
5    False
6      NaN
dtype: object

In [46]:
l=pd.Series([1,2,3,np.nan,4,None,5,pd.NA], dtype="Int32")

In [47]:
l

0       1
1       2
2       3
3    <NA>
4       4
5    <NA>
6       5
7    <NA>
dtype: Int32

In [51]:
q=pd.Series([1,2,3,4,np.nan,5,None], dtype="float")

In [52]:
q

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    5.0
6    NaN
dtype: float64

In [53]:
w=pd.Series([1,2,3,"Natansh",np.nan,4,None])

In [54]:
w

0          1
1          2
2          3
3    Natansh
4        NaN
5          4
6       None
dtype: object

In [55]:
w.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [56]:
w.isna()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [57]:
w.notna()

0     True
1     True
2     True
3     True
4    False
5     True
6    False
dtype: bool

In [58]:
w.notnull()

0     True
1     True
2     True
3     True
4    False
5     True
6    False
dtype: bool

In [59]:
w[w.notnull()]

0          1
1          2
2          3
3    Natansh
5          4
dtype: object

In [60]:
w[w.isnull()]

4     NaN
6    None
dtype: object

In [61]:
w[w.notnull()]

0          1
1          2
2          3
3    Natansh
5          4
dtype: object

In [64]:
w.dropna(inplace=True)

In [65]:
w

0          1
1          2
2          3
3    Natansh
5          4
dtype: object

In [66]:
p

0    NaN
1    1.0
dtype: float64

In [67]:
q

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    5.0
6    NaN
dtype: float64

In [68]:
q.fillna(0)

0    1.0
1    2.0
2    3.0
3    4.0
4    0.0
5    5.0
6    0.0
dtype: float64

In [69]:
q

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    5.0
6    NaN
dtype: float64